services:
  overdrive:
    build: ./overdrive
    volumes:
      - ./overdrive/audiobooks:/Audiobooks
  audible:
    build: ./audible
    volumes:
      - ./audible/audiobooks:/Audiobooks
    environment:
      - AUTHCODE=${AUTHCODE}